const citations = [
    {
        "Page": "3",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "There were airs, waters, places, daughters",
        "Referenced": "De aere, aquis et locis",
        "Author": "Hippocrates",
        "Year": "5th/4th c. BCE",
        "Link": "https://www.britannica.com/topic/Air-Waters-and-Places",
        "File": "",
        "Hover element": "\"In the book Airs, Waters, and Places, thought to have been written by Greek physician Hippocrates in the 5th or 4th century bce, the first systematic attempt was made to set forth a causal relationship between human diseases and the environment.\" (Britannica)",
        "id": 0
    },
    {
        "Page": "3",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Men with bird masks and wheelbarrows",
        "Referenced": "Plague doctor costumes",
        "Author": "",
        "Year": "17th c.",
        "Link": "https://en.wikipedia.org/wiki/Plague_doctor_costume",
        "File": "",
        "Hover element": "\"The clothing worn by plague doctors was intended to protect them from airborne diseases during outbreaks of bubonic plague in Europe.\" (Wikipedia)",
        "id": 1
    },
    {
        "Page": "3",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Just the ginkgos</i>, a parent might say, regarding the smell",
        "Referenced": "Ginkgo biloba",
        "Author": "",
        "Year": "",
        "Link": "https://arboretum.harvard.edu/stories/wake-up-and-smell-the-ginkgos/",
        "File": "",
        "Hover element": "",
        "id": 2
    },
    {
        "Page": "3",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "The dominant metaphor for the brain was the computer",
        "Referenced": "The empty brain",
        "Author": "Robert Epstein",
        "Year": "2016",
        "Link": "https://aeon.co/essays/your-brain-does-not-process-information-and-it-is-not-a-computer",
        "File": "",
        "Hover element": "",
        "id": 3
    },
    {
        "Page": "4",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "<i>Exquisitely dependent</i>, a scientist might say, regarding a spiderweb",
        "Referenced": "Extended spider cognition",
        "Author": "Hilton F. Japyass\u00fa and Kevin N. Laland",
        "Year": "2017",
        "Link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5394149/",
        "File": "",
        "Hover element": "\"Among these behaviours, web building is probably the best studied, with a long tradition of natural history descriptions (Tilquin 1942; Savory 1952; Witt et al. 1968), as well as experimental data concerning a variety of influences on web building. This work reveals the spider\u2019s web to be a structure exquisitely dependent on both major environmental features (Scharf et al. 2011) and self-built cues, based on precise interactions between the spider and actual thread configuration (Peters 1970; Ades 1995).\"",
        "id": 4
    },
    {
        "Page": "4",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>Creamy like a library</i>, someone wrote, regarding madness",
        "Referenced": "I Love Dick",
        "Author": "Chris Kraus",
        "Year": "1998",
        "Link": "",
        "File": "",
        "Hover element": "\"Schizophrenics aren\u2019t sunk into themselves. Associatively, they\u2019re hyperactive. The world gets creamy like a library. And schizophrenics are the most generous of scholars because they\u2019re emotionally right there, they don\u2019t just formulate, observe. They\u2019re willing to become the situated person\u2019s expectations. \u201cThe schizophrenic has lightning access to you,\u201d Fe\u0301lix continued. \u201cHe internalizes all the links between you, makes them part of his subjective system.\u201d This is empathy to the highest power: the schizophrenic turns into a seer, then enacts that vision through his or her becoming. But when does empathy turn into dissolution?\"",
        "id": 5
    },
    {
        "Page": "4",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>Creamy, like certain roses</i>, regarding a woman\u2019s cheeks",
        "Referenced": "In Search of Lost Time, Vol. II",
        "Author": "Marcel Proust",
        "Year": "1913-1927",
        "Link": "https://www.google.com/books/edition/Remembrance_of_Things_Past_Volume_I/CaxA8Uat1XUC?hl=en&gbpv=1&dq=%22I+gazed+at+Albertine%E2%80%99s+cheeks+as+she+spoke,+and+asked+myself+what+might+be+the+perfume,+the+taste+of+them:+that+day+she+was+not+fresh+and+cool+but+smooth,+with+a+uniform+pinkness,+violet-tinted,+creamy,+like+certain+roses+whose+petals+have+a+waxy+gloss.+I+felt+a+passionate+longing+for+them+such+as+one+feels+sometimes+for+a+particular+flower.+%E2%80%9CI+hadn%E2%80%99t+noticed+it,%E2%80%9D+was+all+that+I+said.%22&pg=PA949&printsec=frontcover",
        "File": "",
        "Hover element": "\"I gazed at Albertine\u2019s cheeks as she spoke, and asked myself what might be the perfume, the taste of them: that day she was not fresh and cool but smooth, with a uniform pinkness, violet-tinted, creamy, like certain roses whose petals have a waxy gloss. I felt a passionate longing for them such as one feels sometimes for a particular flower. 'I hadn\u2019t noticed it,' was all that I said.\"",
        "id": 6
    },
    {
        "Page": "4",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>Creamy bursts</i>, regarding flares dropped from choppers",
        "Referenced": "White Noise",
        "Author": "Don DeLillo",
        "Year": "1984",
        "Link": "https://www.google.com/books/edition/White_Noise/rKFyI6Jy0OkC?hl=en&gbpv=1&bsq=creamy",
        "File": "",
        "Hover element": "\"But this was not history we were witnessing. It was some secret festering thing, some dreamed emotion that accompanies the dreamer out of sleep. Flares came swooning from the helicopters, creamy bursts of red and white light. Drivers sounded their horns and children crowded all the windows, faces tilted, pink hands pressed against the glass.\"",
        "id": 7
    },
    {
        "Page": "4",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, a prayer between two flights",
        "Referenced": "Cool Memories II",
        "Author": "Jean Baudrillard",
        "Year": "1987-1990",
        "Link": "https://monoskop.org/images/a/a7/Baudrillard_Jean_Cool_Memories_II_1996.pdf",
        "File": "",
        "Hover element": "\"Showing on five monitors at once are the Lake Placid Olympics, the mirages of the Sahara, the gentle madness of the suburbs, the ecstatic techniques of body-building. Cosy ambience, subdued lighting. The people sink into the creamy sweetness of the non-stop telespectral, a sweetness as creamy as the prayer between two flights in an airport chapel.\"",
        "id": 8
    },
    {
        "Page": "4",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, the inner surface of one thigh",
        "Referenced": "The Adult Life of Toulouse Lautrec ",
        "Author": "Kathy Acker",
        "Year": "1975",
        "Link": "",
        "File": "",
        "Hover element": "\"What would it be like if Marcia one day doesn't resist\u2014if, as my fingers caress the creamy inner surface of one thigh, slightly above the knee, she relaxes, allowing her thighs to open like a book with smooth pages. What then? There comes a softness at the tips of my fingers, a wet, breaking softness under a mat of fragile hair. What does she have deep there, at her pit, between her legs, like a furry animal? Does it have a life of its own? Is it a strange beast lying in wait, with its heaped softness simply bait for the unwary? I'd give anything to know.\"",
        "id": 9
    },
    {
        "Page": "5",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Beneath the paving stones there was not a beach",
        "Referenced": "\"Sous les pav\u00e9s, la plage!\"",
        "Author": "1968 Paris protests",
        "Year": "1968",
        "Link": "https://medium.com/@joelmills66/sous-les-pav%C3%A9s-la-plage-1968-and-the-revolution-that-never-was-d811eb88882e",
        "File": "la-plage.jpg",
        "Hover element": "Slogan from 1968 demonstrations in France (\"Beneath the cobblestones, the beach!\"). <br><br>\n\n\u201c\u2019Sous les pav\u00e9s, la plage!' was one of many inspirational and provocative Situationist slogans to be found in graffiti and posters on the walls and streets of Paris in 1968. The Situationist International had emerged from an avant-garde group of poets, writers, and thinkers in the late 50s, and Guy Debord, perhaps the best known of the collective, had published his book, The Society of the Spectacle, only the previous year. For Debord, The Spectacle, was 'a social relation between people mediated by images in which society co-opted capitalism, creating an inherent alienation, that in turn absorbed dissent. Permeating all areas of social life, knowledge, and culture, people's lives became less about being, increasingly about having, and in a consumer market and media orientated economy, eventually even about 'appearing to have. People became spectators in their own lives, increasingly distant and alienated from their own experiences, creativity, and desires.\u201d",
        "id": 10
    },
    {
        "Page": "6",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "I pet her behind the ears like a little rabbit",
        "Referenced": "Personal experience of the author",
        "Author": "Auden Lincoln-Vogel",
        "Year": "2010s",
        "Link": "",
        "File": "behind-the-ears.jpg",
        "Hover element": "This technique stimulates the vagus nerve, which is connected to the parasympathetic nervous system.",
        "id": 11
    },
    {
        "Page": "6",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "To move the angel, they tied a rope around its neck",
        "Referenced": "\"Does It Make You Feel Alive to Sing?\"",
        "Author": "Annelyse Gelman",
        "Year": "2019",
        "Link": "https://www.youtube.com/watch?v=ZN9XXgketGk",
        "File": "",
        "Hover element": "This line references my song (\"To save the drowning dog, you wrap a rope around its neck / To save the drowning dog, you kill it\"), which itself references Brigit Pegeen Kelly's poem \"Song\" (\"Listen: there was a goat\u2019s head hanging by ropes in a tree\").",
        "id": 12
    },
    {
        "Page": "7",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "An incarcerated man asked for a photograph of the sun",
        "Referenced": "Photo Requests from Solitary",
        "Author": "Tamms Year Ten",
        "Year": "2009-present",
        "Link": "https://photorequestsfromsolitary.org/",
        "File": "",
        "Hover element": "\"Heres what I would like to see in my photo: a nice summer day, Blue sky with lots of sun shining down on trees, grass, flower and perhaps small animals such as birds etc. That is what I'd like to see, Being in solitary confinement with no window or any view of the outside world, I tend to forget what if looks like. Whats funny is that right now its summer time, Yet, I feel as if I\u2019m still waiting for summer since this place obstructs the sun from shining through, Everyday seems like a gray gloomy day. So a picture with the scene I described will be appreciated.\" - Request #80, for John (California)",
        "id": 13
    },
    {
        "Page": "8",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "The entire pluck<br>Could be removed en masse for complete evaluation",
        "Referenced": "How to Perform an Equine Field Necropsy",
        "Author": "Sally L. Ness and Fairfield T. Bain",
        "Year": "2009",
        "Link": "https://aaep.org/sites/default/files/issues/proceedings-09proceedings-z9100109000313.pdf",
        "File": "",
        "Hover element": "\"NOTE: If a more thorough examination of the cardiopulmonary system or cranial mediastinum is required, the forelimb may be reflected dorsally by incising between the scapula and body wall. Reflection of the limb will provide a better view of the cranial thorax and thoracic inlet, but may also make incision closure and replacement of limbs back into normal anatomic position following necropsy difficult. The entire \u2018pluck\u2019 (tongue, larynx, trachea, esophagus, heart and lungs) may be also removed en masse for complete evaluation.\"",
        "id": 14
    },
    {
        "Page": "8",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "The weight of the ice melt slowly tilted the Earth",
        "Referenced": "Rapid ice melting drives Earth's pole to the east (Geophysical Research Letters)",
        "Author": "Chen, Jianli & Wilson, Clark & Ries, J.C. & Tapley, Byron",
        "Year": "2013",
        "Link": "https://www.researchgate.net/publication/258787662_Rapid_ice_melting_drives_Earth%27s_pole_to_the_east",
        "File": "",
        "Hover element": "",
        "id": 15
    },
    {
        "Page": "8",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "As for the starry crown, we didn\u2019t know what to do with it",
        "Referenced": "\"Down to the River to Pray\"",
        "Author": "African-American spiritual, c. 1867",
        "Year": "",
        "Link": "https://www.youtube.com/watch?v=zSif77IVQdY",
        "File": "",
        "Hover element": "As I went down in the valley to pray,<br>\nStudying about that good old way,<br>\nWhen you shall wear the starry crown,<br>\nGood Lord, show me the way.<br>\nO mourner, let's go down, let's go down, let's go down,<br>\nO mourner, let's go down,<br>\nDown in the valley to pray<br>",
        "id": 16
    },
    {
        "Page": "8",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "A shy mimosa cringed when you touched it",
        "Referenced": "Mimosa pudica",
        "Author": "",
        "Year": "",
        "Link": "https://www.nybg.org/poetic-botany/mimosa/",
        "File": "",
        "Hover element": "",
        "id": 17
    },
    {
        "Page": "8",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "A procession of violent images culminating in a fact",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "Criticism of my poetry, c. 2016.",
        "id": 18
    },
    {
        "Page": "9",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Hissing, we hit it with a hockey stick but it wouldn\u2019t budge",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "I witnessed this as a child in Alameda, California.",
        "id": 19
    },
    {
        "Page": "9",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "The cut was wide but not deep, praise be",
        "Referenced": "The Handmaid's Tale",
        "Author": "Margaret Atwood",
        "Year": "1985",
        "Link": "",
        "File": "",
        "Hover element": "\"Praise[d] be\" is a phrase often repeated in Gilead, the repressive religious society depicted in Margaret Atwood's <i>The Handmaid's Tale</i>.",
        "id": 20
    },
    {
        "Page": "9",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "The blood was common-poppy red, the grass chroma-key green",
        "Referenced": "Chroma key",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Chroma_key",
        "File": "",
        "Hover element": "\"Chroma key compositing, or chroma keying, is a visual-effects and post-production technique for compositing (layering) two or more images or video streams together based on colour hues (chroma range).\"",
        "id": 21
    },
    {
        "Page": "10",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "People built a road straight through the base<br>Of the oldest living tree in the world",
        "Referenced": "The Chandelier Tree",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Chandelier_Tree",
        "File": "chandelier-tree-1941.jpg",
        "Hover element": "",
        "id": 22
    },
    {
        "Page": "10",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "The economy of attention was an economy of care",
        "Referenced": "The attention economy",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Attention_economy",
        "File": "",
        "Hover element": "",
        "id": 23
    },
    {
        "Page": "10",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "It was like walking up a tempered-glass staircase into a cloud",
        "Referenced": "The Legend of Zelda: Majora's Mask ",
        "Author": "Nintendo",
        "Year": "2000",
        "Link": "",
        "File": "zelda.png",
        "Hover element": "",
        "id": 24
    },
    {
        "Page": "10",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "From which there was no wisdom one could carry down",
        "Referenced": "Exodus 32:15",
        "Author": "Moses",
        "Year": "c. 1400 BC",
        "Link": "",
        "File": "",
        "Hover element": "\"Then Moses turned and went down the mountain with the two tablets of the Testimony in his hands. They were inscribed on both sides, front and back. The tablets were the work of God, and the writing was the writing of God, engraved on the tablets.\u2026\"",
        "id": 25
    },
    {
        "Page": "10",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "Acts of God, sending thoughts, nonbreaking space",
        "Referenced": "\"Thoughts and prayers\"",
        "Author": "American politicians",
        "Year": "c. 2010s-present",
        "Link": "https://en.wikipedia.org/wiki/Thoughts_and_prayers",
        "File": "",
        "Hover element": "",
        "id": 26
    },
    {
        "Page": "11",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Willows along the canal were smothered in something cotton candy\u2013esque",
        "Referenced": "Ermine moth larvae (Gespinstmottenraupen)",
        "Author": "",
        "Year": "",
        "Link": "https://allaboutberlin.com/guides/worms-in-trees",
        "File": "ermine-moth-tree.jpg",
        "Hover element": "",
        "id": 27
    },
    {
        "Page": "11",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "<i>Creamy pudding</i>, someone wrote, regarding knowledge",
        "Referenced": "Teaching to Transgress: Education as the Practice of Freedom",
        "Author": "bell hooks",
        "Year": "2014",
        "Link": "https://edisciplinas.usp.br/mod/resource/view.php?id=2559296",
        "File": "creamy-bellhooks.png",
        "Hover element": "\"It is as though we are to imagine that knowledge is this rich creamy pudding students should consume and be nourished by, but not that the process of gestation should also be pleasurable.\"",
        "id": 28
    },
    {
        "Page": "11",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "A scheme always failed if you watched it being hatched",
        "Referenced": "\"Unspoken plan guarantee\" trope",
        "Author": "",
        "Year": "",
        "Link": "https://tvtropes.org/pmwiki/pmwiki.php/Main/UnspokenPlanGuarantee",
        "File": "",
        "Hover element": "\"The chances of The Plan succeeding are inversely proportional to how much of the plan the audience knows about beforehand.\" -TV Tropes",
        "id": 29
    },
    {
        "Page": "11",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "Like that woman who couldn\u2019t pour a cup of tea<br>Because it was<i> frozen, like a glacier</i>",
        "Referenced": "Selective Disturbance of Movement Vision after Bilateral Brain Damage \u2014\u00a0Brain (1983), 106,313-340",
        "Author": "J. Zihl, D. Von Cramon, and N. Mai ",
        "Year": "1983",
        "Link": "https://pubmed.ncbi.nlm.nih.gov/6850272/",
        "File": "glacier.png",
        "Hover element": "\"The visual disorder complained of by the patient was a loss of movement vision in all three dimensions. She had difficulty, for example, in pouring tea or coffee into a cup because the fluid appeared to be frozen, like a glacier. In addition, she could not stop pouring at the right time since she was unable to perceive the movement in the cup (or a pot) when the fluid rose. Furthermore the patient complained of difficulties in following a dialogue because she could not see the movements of the face and, especially, the mouth of the speaker. In a room where more than two other people were walking she felt very insecure and unwell, and usually left the room immediately, because 'people were suddenly here or there but I have not seen them moving'. The patient experienced the same problem but to an even more marked extent in crowded streets or places, which she therefore avoided as much as possible. She could not cross the street because of her inability to judge the speed of a car, but she could identify the car itself without difficulty. 'When I'm looking at the car first, it seems far away. But then, when I want to cross the road, suddenly the car is very near.' She gradually learned to 'estimate' the distance of moving vehicles by means of the sound becoming louder.\"",
        "id": 30
    },
    {
        "Page": "11",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Sometimes a brain got too big, holes had to be drilled",
        "Referenced": "Trepanation",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Trepanning",
        "File": "",
        "Hover element": "",
        "id": 31
    },
    {
        "Page": "11",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>People always want more, no matter how much they have already</i>",
        "Referenced": "Economics: Concepts and Choices",
        "Author": "McDougal Littell",
        "Year": "2008",
        "Link": "https://www.yourcharlotteschools.net/cms/lib/FL02211872/Centricity/Domain/4236/Economics%20Textbook.pdf",
        "File": "scarcity.png",
        "Hover element": "\"Have you ever felt you wanted a new cell phone, a car, a new pair of running shoes, or the latest MP3 player? You are not alone. Consumers have many economic wants. Wants are desires that can be satisfied by consuming a good or service. When making purchases, people often make a distinction between the things they need and the things they want. Some things that people desire, like a house or an apartment, are more important than other things, like a flat-screen television. Needs are things, such as food, clothing, and shelter, that are necessary for survival.<br><br>\nPeople always want more, no matter how much they have already. In fact, wants are unlimited, but the resources available to satisfy them are limited. The result of this difference is scarcity, the situation that exists when there are not enough resources to meet human wants.\"",
        "id": 32
    },
    {
        "Page": "11",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "A figure\u2019s hand was still encased in the marble block",
        "Referenced": "Auguste Rodin",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\"No good sculptor can model a human figure without dwelling on the mystery of life; this individual and that in fleeting variations only reminds him of the immanent type; he is led perpetually from the creature to the creator. All the best works of any artist must be bathed, so to speak, in mystery. That is why many of my figures have a hand, a foot still imprisoned in the marble block; life is everywhere, but rarely indeed does it come to complete expression or the individual to perfect freedom.\"<br>",
        "id": 33
    },
    {
        "Page": "12",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "In a fake Russian schoolhouse an intern sprinkled <br>Fake dust onto the fake wooden school desk",
        "Referenced": "School No. 6",
        "Author": "Ilya Kabakov",
        "Year": "1993",
        "Link": "https://chinati.org/collection/ilya-kabakov/",
        "File": "",
        "Hover element": "An artwork in Marfa, Texas.<br><br>\"Ilya Kabakov created School No. 6 in 1993 as a gift to the Chinati Foundation. The work occupies an entire building that is subdivided into rooms reminiscent of an abandoned schoolhouse from the former Soviet Union. The spaces are filled with faded posters, flags, and emblems; everything is broken, boarded-up, and neglected. Bookcases and desks with Russian notebooks and memorabilia scattered throughout the disordered classrooms tell an elliptical story about another place and time. The walls are painted an institutional green, which is peeling. In the center of the building is a courtyard overgrown with grass and weeds. In faded red, glass-enclosed vitrines, Kabakov\u2019s poetic writing recounts the stories and recollections of the students\u2019 past experience in the school.\"",
        "id": 34
    },
    {
        "Page": "12",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "People built robots to clean the dust off solar panels",
        "Referenced": "21st-century technology",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "solarcleano.png",
        "Hover element": "",
        "id": 35
    },
    {
        "Page": "12",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Birds flew through the light and were cooked in midair",
        "Referenced": "\"Streamers\"",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\u201cOpened in 2014, the largest solar power plant in the world, Ivanpah Solar Plant, located in the Mojave Desert in California, is believed to be responsible for at least 6,000 bird deaths each year, as the birds can suffer severe burns or become incinerated if they fly too close to the 40-foot towers that concentrate sunlight from five square miles of solar panels. These numbers are likely an underestimation, as the sight of birds and insects rapidly immolated as they soar too close to the towers, which can reach temperatures of 1000 degrees Fahrenheit, is so common that staff at the plant have a name for them; \u201cstreamers\u201d.\u201d\n<br>\u2014 Association of Avian Veterans",
        "id": 36
    },
    {
        "Page": "12",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Over the PA someone said, <i>A diamond is forever!</i>",
        "Referenced": "De Beers Group advertising slogan",
        "Author": "Frances Gerety",
        "Year": "1947",
        "Link": "https://www.debeersgroup.com/about-us/a-diamond-is-forever",
        "File": "",
        "Hover element": "",
        "id": 37
    },
    {
        "Page": "12",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "And she cried when the fox said, <i>Please\u2014tame me</i>!",
        "Referenced": "The Little Prince (Le Petit Prince)",
        "Author": "Antoine de Saint-Exup\u00e9ry",
        "Year": "1943",
        "Link": "https://en.wikipedia.org/wiki/The_Little_Prince",
        "File": "tame-me.jpg",
        "Hover element": "\"The Trump administration has set up at least three \u201ctender age\u201d shelters to detain babies and other young children who have been forcibly separated from their parents at the U.S.-Mexico border, The Associated Press has learned. Doctors and lawyers who have visited the shelters in South Texas\u2019 Rio Grande Valley said the facilities were fine, clean and safe, but the children \u2014 who have no idea where their parents are \u2014 were hysterical, crying and acting out. Many of them are under age 5, and some are so young they have not yet learned to talk.\"",
        "id": 38
    },
    {
        "Page": "13",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "There was a poster of a painting of a girl about daughter\u2019s age, standing in a snowy field",
        "Referenced": "\"Love Hunter II\" ",
        "Author": "Michael Cheval",
        "Year": "2015",
        "Link": "https://www.fascinationstart.com/artwork/sku28198",
        "File": "cheval-hunter.jpg",
        "Hover element": "I saw this painting hanging in the offices of the psychiatry service Psych Dimensions in Austin, TX. There was also an aquarium in the room. <br><br>Michael Cheval's statement on <i>Love Hunter II</i>: \"Love is not just roses, sighing in the moonlight and gentle words. Love is a real war. A man and a woman hunt for each other. And someone in the war wins and someone loses. It is very important that a loser doesn\u2019t realize that he had lost. On this hunt, as in a war, all expedients are good. To hunt down, and gently entice a win. This lady-hunter has a beautiful weapon. Delicate lute imperceptibly turns into the [crossbow]. Rabbits popping out of her satin skirt\u2014it is what she is complete\u2014they symbolize her desire.\"",
        "id": 39
    },
    {
        "Page": "13",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "The article called the tundra a <i>giant white layer cake</i>",
        "Referenced": "B-46, Pine Island Glacier, West Antarctica",
        "Author": "National Geographic",
        "Year": "2018",
        "Link": "https://www.nationalgeographic.com/environment/article/exclusive-first-pictures-of-iceberg-three-times-the-size-of-manhattan",
        "File": "b-46.jpg",
        "Hover element": "\"Moments later, the cracks appeared. Huge, blocky fissures sliced across the giant white layer cake of the Pine Island Glacier, a fast-moving part of the West Antarctic ice sheet. The sound of clicking shutters filled the noisy, drafty cabin of the DC-8. There were broad smiles and exclamations. \u201cIt\u2019s so big,\u201d someone said. \u201cIt\u2019s incredible,\u201d said another.\"",
        "id": 40
    },
    {
        "Page": "13",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "\u2014<i>I think something\u2019s wrong with me</i>, said daughter",
        "Referenced": "\"Grasshopper\"",
        "Author": "Annelyse Gelman",
        "Year": "2019",
        "Link": "https://soundcloud.com/sleepingin/grasshopper",
        "File": "",
        "Hover element": "I wrote the song \"Grasshopper\" in 2019 at the Fondation Jan Michalski, where I also composed <i>Vexations</i>. The song's \"I think something's wrong with me\" is spoken by a boy, and the episode is based on a story told to me by my friend Jason Grier.",
        "id": 41
    },
    {
        "Page": "14",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "We had a word for stepping on someone\u2019s face with a boot",
        "Referenced": "1984",
        "Author": "George Orwell",
        "Year": "1949",
        "Link": "https://rauterberg.employee.id.tue.nl/lecturenotes/DDM110%20CAS/Orwell-1949%201984.pdf",
        "File": "",
        "Hover element": "\"There will be no loyalty, except loyalty towards the Party. There will be no love, except the love of Big Brother. There will be no laughter, except the laugh of triumph over a defeated enemy. There will be no art, no literature, no science. When we are omnipotent we shall have no more need of science. There will be no distinction between beauty and ugliness. There will be no curiosity, no enjoyment of the process of life. All competing pleasures will be destroyed. But always\u2014do not forget this, Winston\u2014always there will be the intoxication of power, constantly increasing and constantly growing subtler. Always, at every moment, there will be the thrill of victory, the sensation of trampling on an enemy who is helpless. If you want a picture of the future, imagine a boot stamping on a human face\u2014for ever.\"",
        "id": 42
    },
    {
        "Page": "14",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Who would preserve the smell of an expired carton of milk?",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "milk-joke.jpg",
        "Hover element": "An old joke (not sure of the origin, and certainly not original to this cartoon).",
        "id": 43
    },
    {
        "Page": "14",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "The specialist said, <i>Persistent and indiscriminate receptivity</i>",
        "Referenced": "Boredom",
        "Author": "Siegfried Kracauer",
        "Year": "1924",
        "Link": "https://schwarzemilch.wordpress.com/wp-content/uploads/2009/02/3103-boredom.pdf",
        "File": "",
        "Hover element": "\u201cRadio likewise vaporizes beings, even before they have intercepted a single spark. Since many people feel compelled to broadcast, one finds oneself in a state of permanent receptivity, constantly pregnant with London, the Eiffel Tower, and Berlin. Who would want to resist the invitation of those dainty headphones? They gleam in living rooms and entwine themselves around heads all by themselves; and instead of fostering cultivated conversation (which certainly can be a bore), one becomes a playground for worldwide noises that, regardless of their own potentially objective boredom, do not even grant one's modest right to personal boredom. Silent and lifeless, people sit side by side as if their souls were wandering about far awav. But these souls are not wandering according to their own preference; they are badgered by the news hounds, and soon no one can tell anymore who is the hunter and who is the hunted. Even in the cafe, where one wants to roll up into a ball like a porcupine and become aware of one's insignificance, an imposing loudspeaker effaces every trace of private existence. The announcements it blares forth dominate the space of the concert intermissions, and the waiters (who are listening to it themselves) indignantly refuse the unreasonable requests to get rid of this gramophonic mimicry.\n\nAs one is enduring this species of antennal fate, the five continents are drawing ever closer. In truth, it is not we who extend ourselves out toward them; rather, it is their cultures that appropriate us in their boundless imperialism. It is as if one were having one of those dreams provoked by an empty stomach: a tiny ball rolls toward you from very far away, expands into a close-up, and finally roars right over you. You can neither stop it nor escape it, but lie there chained, a helpless little doll swept away by the giant colossus in whose ambit it expires. Flight is impossible.\u201d",
        "id": 44
    },
    {
        "Page": "15",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "The box stridulated and daughter opened the lid",
        "Referenced": "Stridulation",
        "Author": "",
        "Year": "",
        "Link": "https://www.amentsoc.org/insects/glossary/terms/stridulation/#:~:text=Stridulation%20is%20the%20act%20of,are%20the%20grasshoppers%20and%20crickets.",
        "File": "",
        "Hover element": "There were many grasshoppers in the summer of 2019 in Montricher, Switzerland, where I wrote Vexations. I closely observed them and made sketches and music. \"Stridulation is the act of producing sound, usually by rubbing two body parts together. Some of the most well known insects that stridulate are the grasshoppers and crickets.\"",
        "id": 45
    },
    {
        "Page": "15",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "<i>Creamy smoothness</i>, someone wrote, regarding a fog-wreathed sea",
        "Referenced": "\"'Psychical Distance' as a Factor in Art and as an Aesthetic Principle\"",
        "Author": "Edward Bullough",
        "Year": "1912",
        "Link": "http://web.csulb.edu/~jvancamp/361_r9.html",
        "File": "",
        "Hover element": "\"A short illustration will explain what is meant by 'Psychical Distance.' Imagine a fog at sea; for most people it is an experience of acute unpleasantness. Apart from the physical annoyance and remoter forms of discomfort such as delays, it is apt to produce feelings of peculiar anxiety, fears of invisible dangers, strains of watching and listening for distant and unlocalised signals. The listless movements of the ship and her warning calls soon tell upon the nerves of the passengers; and that special, expectant, tacit anxiety and nervousness, always associated with this experience, make a fog the dreaded terror of the sea (all the more terrifying because of its very silence and gentleness) for the expert seafarer no less than the ignorant landsman. #4. Nevertheless, a fog at sea can be a source of intense relish and enjoyment. Abstract from the experience of the sea fog, for the moment, its danger and practical unpleasantness, just as every one in the enjoyment of a mountain-climb disregards its physical labour and its dancer (though, it is not denied, that these may incidentally enter into the enjoyment and enhance it); direct the attention to the features 'objectively' constituting the phenomenon - the veil surround you with an opaquensss as of transparent milk, blurring the outline of things and distorting their shapes into weird grotesqueness; observe the carrying-power of the air, producing the impression as if you could touch some far-off siren by merely putting out your hand and letting it lose itself behind that white wall; note the curious creamy smoothness of the water, hypocritically denying as it were any suggestion of dancer; and, above all, the strange solitude and remoteness from the world, as it can be found only on the highest mountain tops; and the experience may acquire, in its uncanny mingling of repose and terror, a flavour of such concentrated poignancy and delight as to contrast sharply with the blind and distempered anxiety of its other aspects. This contrast, often emerging with startling suddenness, is like a momentary switching on of some new current, or the passing ray of a brighter light, illuminating the outlook upon perhaps the most ordinary and familiar objects - an impression which we experience sometimes in instants of direct extremity, when our practical interest snaps like a wire from sheer over-tension, and we watch the consummation of some impending catastrophe with the marvelling unconcern of a mere spectator. #5. It is a difference of outlook, due - if such a metaphor is permissible - to the insertion of distance. This distance appears to lie between our own self and its affections, using the latter term in its broadest sense as anything which affects our being, bodily or spiritually, e.g., as sensation, perception, emotional state or idea. Usually, though not always, it amounts to the same thing to say that the Distance lies between our own self and such objects as are the sources or vehicles of such affections.\"",
        "id": 46
    },
    {
        "Page": "15",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "A little nectar was enough to make two hummingbirds",
        "Referenced": "",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "I saw this during an extended visit to the Gila National Forest in New Mexico in the summer of 2014.",
        "id": 47
    },
    {
        "Page": "15",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "<i>The plant is the leaf</i>, went the saying",
        "Referenced": "The Life of Plants: A Metaphysics of Mixture",
        "Author": "Emanuele Coccia",
        "Year": "2018",
        "Link": "https://www.wiley.com/en-us/The+Life+of+Plants%3A+A+Metaphysics+of+Mixture-p-9781509531523",
        "File": "",
        "Hover element": "\u201cLeaves are not just the principal part of the plant. Leaves <i>are</i> the plant: trunk and root are parts of the leaf, the base of the leaf, the simple extension by which leaves, in staying high up in the air, are supported by and nourish themselves from the soil. [\u2026] The whole plant is identified in the leaf, to which the other organs are just appendages. It is the leaf that produces the plant: leaves form the flower, the sepals, the petals, the stamens, the pistils; and it is also the leaves that form the fruit.\" <br><br>(As quoted from an Italitan text in Coccia.)",
        "id": 48
    },
    {
        "Page": "15",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "The form of the danger was an emanation of energy",
        "Referenced": "Expert judgment on markers to deter inadvertent human intrusion into the Waste Isolation Pilot Plant",
        "Author": "Sandia National Laboratories",
        "Year": "1993",
        "Link": "https://digital.library.unt.edu/ark:/67531/metadc1279277/m2/1/high_res_d/10117359.pdf",
        "File": "",
        "Hover element": "\"Some of the archetypal feelings and meanings we will explore in design of the markers for the WIPP site are those of danger to the body; darkness; fear of the beast; pattern breaking chaos and loss-of-control; dark forces emanating from within; the void or abyss; rejection of inhabitation; parched, poisoned and plagued land...and others.\"",
        "id": 49
    },
    {
        "Page": "15",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "As for the youngest, there were tender age facilities",
        "Referenced": "\"At least 3 \u201ctender age\u201d shelters set up for child migrants\"",
        "Author": "AP News",
        "Year": "2018",
        "Link": "https://apnews.com/article/north-america-us-news-ap-top-news-mi-state-wire-immigration-dc0c9a5134d14862ba7c7ad9a811160e#:~:text=The%20Trump%20administration%20has%20set,The%20Associated%20Press%20has%20learned.",
        "File": "",
        "Hover element": "\"The Trump administration has set up at least three \u201ctender age\u201d shelters to detain babies and other young children who have been forcibly separated from their parents at the U.S.-Mexico border, The Associated Press has learned. Doctors and lawyers who have visited the shelters in South Texas\u2019 Rio Grande Valley said the facilities were fine, clean and safe, but the children \u2014 who have no idea where their parents are \u2014 were hysterical, crying and acting out . Many of them are under age 5, and some are so young they have not yet learned to talk.\"",
        "id": 50
    },
    {
        "Page": "15",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "We worshipped progress, there was nothing else to worship",
        "Referenced": "This Is Water",
        "Author": "David Foster Wallace",
        "Year": "2005",
        "Link": "http://bulletin-archive.kenyon.edu/x4280.html",
        "File": "",
        "Hover element": "\"Because here's something else that's true. In the day-to-day trenches of adult life, there is actually no such thing as atheism. There is no such thing as not worshipping. Everybody worships. The only choice we get is what to worship. And an outstanding reason for choosing some sort of God or spiritual-type thing to worship\u2014be it J.C. or Allah, be it Yahweh or the Wiccan mother-goddess or the Four Noble Truths or some infrangible set of ethical principles\u2014is that pretty much anything else you worship will eat you alive. If you worship money and things-if they are where you tap real meaning in life-then you will never have enough. Never feel you have enough. It's the truth. Worship your own body and beauty and sexual allure and you will always feel ugly, and when time and age start showing, you will die a million deaths before they finally plant you. On one level, we all know this stuff already-it's been codified as myths, proverbs, clich\u00e9s, bromides, epigrams, parables: the skeleton of every great story. The trick is keeping the truth up-front in daily consciousness. Worship power-you will feel weak and afraid, and you will need ever more power over others to keep the fear at bay. Worship your intellect, being seen as smart-you will end up feeling stupid, a fraud, always on the verge of being found out. And so on.\"",
        "id": 51
    },
    {
        "Page": "15",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>Pain is weakness leaving</i>, went the saying",
        "Referenced": "\"Pain is weakness leaving the body\"",
        "Author": "United States Marine Corps",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 52
    },
    {
        "Page": "16",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "<i>If you become a little boy and run into a house, said the mother bunny,</i> I said",
        "Referenced": "The Runaway Bunny",
        "Author": "Margaret Wise Brown",
        "Year": "1942",
        "Link": "https://en.wikipedia.org/wiki/The_Runaway_Bunny",
        "File": "",
        "Hover element": "",
        "id": 53
    },
    {
        "Page": "16",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "<i>I will become your mother and catch you in my arms and hug you</i>, I said",
        "Referenced": "The Runaway Bunny",
        "Author": "Margaret Wise Brown",
        "Year": "1942",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 54
    },
    {
        "Page": "16",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "I read her the book about the little rabbit<br>Who says goodnight to every object in the room",
        "Referenced": "Goodnight Moon",
        "Author": "Margaret Wise Brown",
        "Year": "1947",
        "Link": "",
        "File": "goodnight-moon.png",
        "Hover element": "",
        "id": 55
    },
    {
        "Page": "17",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Over the PA someone said, <i>If mine eye offend thee, pluck it out</i>",
        "Referenced": "Matthew 5:29",
        "Author": "St. Matthew the Evangelist",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\"And if thy right eye offend thee, pluck it out, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell.\"",
        "id": 56
    },
    {
        "Page": "17",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "\u2014<i>The air is coming inside me</i>, said daughter",
        "Referenced": "Nausea",
        "Author": "Jean-Paul Sartre",
        "Year": "1938",
        "Link": "",
        "File": "",
        "Hover element": "\"Objects should not touch because they are not alive. You use them, put them back in place, you live among them: they are useful, nothing more. But they touch me, it is unbearable. I am afraid of being in contact with them as though they were living beasts.\"",
        "id": 57
    },
    {
        "Page": "17",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Sweeping water back into the wine-dark sea",
        "Referenced": "The Iliad",
        "Author": "Homer",
        "Year": "8th c. BC",
        "Link": "",
        "File": "",
        "Hover element": "A frequently-used Homeric epithet.",
        "id": 58
    },
    {
        "Page": "19",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Th\u00e9r\u00e8se, her thin red sweater, her Peter Pan collar, all adjectives . . .",
        "Referenced": "Th\u00e9r\u00e8se on a Bench-Seat (Th\u00e9r\u00e8se sur une banquette)",
        "Author": "Balthus",
        "Year": "1939",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 59
    },
    {
        "Page": "20",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "A new hospital was the same place in a different location",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "My father once said this about the fast-food chain restaurant In-N-Out.",
        "id": 60
    },
    {
        "Page": "20",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "The dog barked at the moon but it wouldn\u2019t come down",
        "Referenced": "Blue Thinks The Moon Is Her Ball Again",
        "Author": "Jessie Raspbury",
        "Year": "2016",
        "Link": "https://www.youtube.com/watch?v=rKs604lF-tY&t=1s",
        "File": "",
        "Hover element": "",
        "id": 61
    },
    {
        "Page": "20",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Birds in clear-cut woods mimicked heavy machinery",
        "Referenced": "Lyrebirds, mockingbirds",
        "Author": "",
        "Year": "",
        "Link": "https://www.youtube.com/watch?v=mSB71jNq-yQ",
        "File": "",
        "Hover element": "",
        "id": 62
    },
    {
        "Page": "21",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "<i>Every leaf of every tree of every wood</i>, went the saying",
        "Referenced": "\"Funes the Memorious\"",
        "Author": "Jorge Luis Borges",
        "Year": "1962",
        "Link": "",
        "File": "",
        "Hover element": "\"In effect, Funes not only remembered every leaf on every tree of every wood, but even every one of the times he had perceived or imagined it. He determined to reduce all of his past experience to some seventy thousand recollections, which he would later define numerically. Two considerations dissuaded him: the thought that the task was interminable and the thought that it was useless. He knew that at the hour of his death he would scarcely have finished classifying even all the memories of his childhood.\"",
        "id": 63
    },
    {
        "Page": "21",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "On the grass the dusk just sort of sat there",
        "Referenced": "\"A Blessing\"",
        "Author": "James Wright",
        "Year": "1963",
        "Link": "https://poets.org/poem/blessing",
        "File": "",
        "Hover element": "A mutilation of Wright's line: \"Twilight bounds softly forth on the grass.\"",
        "id": 64
    },
    {
        "Page": "21",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Over the PA someone said, <i>Eram quod es, eris quod sum</i>",
        "Referenced": "Epitaphs",
        "Author": "Horace",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\"I was what you are; you will be what I am.\" Often written on gravestones.",
        "id": 65
    },
    {
        "Page": "21",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "The street, praise be, daughter\u2019s little shadow in the big orange",
        "Referenced": "The Handmaid's Tale",
        "Author": "Margaret Atwood",
        "Year": "1985",
        "Link": "",
        "File": "",
        "Hover element": "\"Praise[d] be\" is a phrase often repeated in Gilead, the repressive religious society depicted in Margaret Atwood's <i>The Handmaid's Tale</i>.",
        "id": 66
    },
    {
        "Page": "22",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "A rabbit looked like undetached rabbit parts",
        "Referenced": "On the Reasons for Indeterminacy of Translation",
        "Author": "Willard Van Orman Quine",
        "Year": "1970",
        "Link": "https://www.jstor.org/stable/2023887",
        "File": "",
        "Hover element": "",
        "id": 67
    },
    {
        "Page": "22",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding ocean waves",
        "Referenced": "The Lotos-eaters",
        "Author": "Alfred, Lord Tennyson",
        "Year": "1832",
        "Link": "https://www.poetryfoundation.org/poems/45364/the-lotos-eaters",
        "File": "",
        "Hover element": "\"And tender curving lines of creamy spray\"",
        "id": 68
    },
    {
        "Page": "22",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding the inner arm",
        "Referenced": "\"Collude\"",
        "Author": "Bhanu Kapil",
        "Year": "2019",
        "Link": "https://poets.org/poem/collude",
        "File": "",
        "Hover element": "\"What color is the skin of your inner arm, creamy?\"",
        "id": 69
    },
    {
        "Page": "22",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding the attire of musicians",
        "Referenced": "\"The Instruction Manual\"",
        "Author": "John Ashbery",
        "Year": "1956",
        "Link": "https://www.poetryfoundation.org/poems/47766/the-instruction-manual",
        "File": "",
        "Hover element": "\"And the musicians mingle among them, in their creamy white uniforms, and talk\"",
        "id": 70
    },
    {
        "Page": "22",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding trees in Boston",
        "Referenced": "\"My Father Was White but Not Quite\"",
        "Author": "Fanny Howe",
        "Year": "2008",
        "Link": "https://www.poetryfoundation.org/poetrymagazine/articles/69163/my-father-was-white-but-not-quite",
        "File": "",
        "Hover element": "\"When I am back in Boston in 2000 a soft snow is falling diagonally. There is no wind. The trees are creamy and drooping.\"",
        "id": 71
    },
    {
        "Page": "22",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding a painting of a lemon",
        "Referenced": "The Potions Master's Nephew: A Harry Potter Fanfiction",
        "Author": "SeverelySnaped",
        "Year": "2009",
        "Link": "http://the-potions-masters-nephew.com/",
        "File": "",
        "Hover element": "\"Ginny grinned to herself and followed a running Snape. \"I hope it's empty...\" she murmured, catching up and standing in front of a creamy picture of a lemon.\"",
        "id": 72
    },
    {
        "Page": "23",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "You could either tumble or run, run or tumble",
        "Referenced": "Howard C. Berg",
        "Author": "E. coli in motion",
        "Year": "2005",
        "Link": "https://books.google.com/books/about/E_coli_in_Motion.html?id=qyVoI1iUiBkC",
        "File": "",
        "Hover element": "",
        "id": 73
    },
    {
        "Page": "23",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Organ, an organ without a body",
        "Referenced": "Gilles Deleuze",
        "Author": "Anti-Oedipus: Capitalism and Schizophrenia",
        "Year": "1977",
        "Link": "https://books.google.com/books/about/Anti_Oedipus.html?id=-P_aAAAAMAAJ",
        "File": "",
        "Hover element": "",
        "id": 74
    },
    {
        "Page": "23",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "On mountains people practiced drawing circles",
        "Referenced": "Ens\u014d",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Ens%C5%8D",
        "File": "",
        "Hover element": "",
        "id": 75
    },
    {
        "Page": "24",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "We were compelled to adventure like the last prince cut his hair",
        "Referenced": "Princess Mononoke",
        "Author": "Hayao Miyazaki",
        "Year": "1997",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 76
    },
    {
        "Page": "24",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "As for the trouble, we didn\u2019t know how to stay with it",
        "Referenced": "Staying with the Trouble: Making Kin in the Chthulucene",
        "Author": "Donna Haraway",
        "Year": "2016",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 77
    },
    {
        "Page": "24",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Children had bad man practice to rehearse the obligatory song",
        "Referenced": "US school shootings: Lullaby used to teach drills",
        "Author": "",
        "Year": "2018",
        "Link": "https://www.bbc.com/news/world-us-canada-44411208",
        "File": "",
        "Hover element": "\"Lockdown, lockdown, lock the door. Shut the lights off, say no more.\"",
        "id": 78
    },
    {
        "Page": "24",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy lake</i>, someone wrote, regarding the object of passion",
        "Referenced": "The Broom of the System",
        "Author": "David Foster Wallace",
        "Year": "1987",
        "Link": "",
        "File": "",
        "Hover element": "\u201cA kiss with Lenore is a scenario in which I skate with buttered soles over the moist rink of lower lip, sheltered from weathers by the wet warm overhang of upper, finally to crawl between lip and gum and pull the lip to me like a child\u2019s blanket and stare over it with beady, unfriendly eyes out at the world external to Lenore, of which I no longer wish to be part. That I must in the final analysis remain part of the world that is external to and other from Lenore Beadsman is to me a source of profound grief. That others may dwell deep, deep within the ones they love, drink from the soft cup at the creamy lake at the center of the Object of Passion, while I am fated forever only to intuit the presence of deep recesses while I poke my nose, as it were, merely into the foyer of the Great House of Love, agitate briefly, and make a small mess on the doormat, pisses me off to no small degree. But that Lenore finds such tiny frenzies, such conversations just inside the Screen Door of Union, to be not only pleasant and briefly diverting but somehow apparently right, fulfilling, significant, in some sense wonderful, quite simply and not at all surprisingly makes me feel the same way, enlarges my sense of it and me, sends me hurrying up the walk to that Screen Door in my best sportjacket and flower in lapel as excited as any schoolboy, time after time, brings me charging to the cave entrance in leopardskin shirt, avec club, bellowing for admittance and promising general kickings of ass if I am impeded in any way.\u201d",
        "id": 79
    },
    {
        "Page": "24",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy moons</i>, someone wrote, regarding hothouse chrysanthemums shining through the golden gloom",
        "Referenced": "Anne of the Island",
        "Author": "Lucy Maud Montgomery",
        "Year": "1915",
        "Link": "",
        "File": "",
        "Hover element": "\"The firelight shadows were dancing over the walls; the cats were purring; and a huge bowl of hothouse chrysanthemums, sent to Phil by one of the victims, shone through the golden gloom like creamy moons.\"",
        "id": 80
    },
    {
        "Page": "24",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy as a cat</i>, someone wrote, regarding excitement",
        "Referenced": "Sylvia Plath",
        "Author": "The Journals of Sylvia Plath",
        "Year": "1982",
        "Link": "",
        "File": "",
        "Hover element": "\"August 8, Friday. \"He is the transparence of the place in which He is and in his poems we find peace.\" \n- Stevens\"\n<br><br>\n\"I am awestruck, excited, smiling inside creamy as a cat: The day has evaporated, quite gone, in a rapt contemplation of my poem \"Mussel Hunter at Rock Harbor,\" which came out in the August 9 issue of the blessed glossy New Yorker\u2014the title in that queer, wobbly, half-archaic type I've dreamed poem and story titles in for about eight years. Queerest of all, I dreamed the poem would come out last night!\"",
        "id": 81
    },
    {
        "Page": "24",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy iridescent coats of mail</i>, someone wrote, regarding wheelbarrows",
        "Referenced": "\"At the Fishhouses\"",
        "Author": "Elizabeth Bishop",
        "Year": "1948",
        "Link": "https://www.poetryfoundation.org/poems/52192/at-the-fishhouses",
        "File": "",
        "Hover element": "The big fish tubs are completely lined<br>\nwith layers of beautiful herring scales<br>\nand the wheelbarrows are similarly plastered<br>\nwith creamy iridescent coats of mail,<br>\nwith small iridescent flies crawling on them.",
        "id": 82
    },
    {
        "Page": "24",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding a beige wall being looked at by someone who wasn\u2019t anxious",
        "Referenced": "Letters from Max",
        "Author": "Sarah Ruhl & Max Ritvo",
        "Year": "2018",
        "Link": "",
        "File": "",
        "Hover element": "\"The creamy beige of the wall just sort of flows through you like vanilla ice cream\u2026\"",
        "id": 83
    },
    {
        "Page": "24",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy drops of mammalian weather</i>, someone wrote, regarding the tears of the sun",
        "Referenced": "\"That Rat's Death\"",
        "Author": "Eileen Myles",
        "Year": "2015",
        "Link": "https://www.poetryfoundation.org/poetrymagazine/poems/57741/that-rats-death",
        "File": "",
        "Hover element": "",
        "id": 84
    },
    {
        "Page": "24",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Daughter wanted to know if this would be forever",
        "Referenced": "David After Dentist",
        "Author": "David DeVore Jr.",
        "Year": "2009",
        "Link": "https://www.youtube.com/watch?v=txqiwrbYGrs",
        "File": "",
        "Hover element": "",
        "id": 85
    },
    {
        "Page": "25",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "The abandoned film set was the ruins of our civilization",
        "Referenced": "In the Land of Drought",
        "Author": "Julian Rosefeldt",
        "Year": "2017",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 86
    },
    {
        "Page": "25",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "The caption said,<i> Is our world gone? We say \u201cFarewell\u201d</i>",
        "Referenced": "Official passport, United States of America",
        "Author": "Lyndon B. Johnson",
        "Year": "",
        "Link": "",
        "File": "farewell.jpg",
        "Hover element": "",
        "id": 87
    },
    {
        "Page": "26",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Scientists put jellyfish genes in a rabbit",
        "Referenced": "Scientists breed glow-in-the-dark rabbits",
        "Author": "",
        "Year": "2013",
        "Link": "https://www.theguardian.com/world/2013/aug/13/glow-in-dark-rabbits-scientists",
        "File": "",
        "Hover element": "",
        "id": 88
    },
    {
        "Page": "26",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "On an intercity bus a person decapitated another person",
        "Referenced": "Horror on Canadian bus as man beheaded",
        "Author": "",
        "Year": "2008",
        "Link": "https://www.reuters.com/article/idUSN31502302/",
        "File": "",
        "Hover element": "",
        "id": 89
    },
    {
        "Page": "27",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "The guy behind the camera asked kids to speak in tongues",
        "Referenced": "Primitive Technology",
        "Author": "",
        "Year": "2010s",
        "Link": "https://www.youtube.com/watch?v=XpJ8K1kt8m8",
        "File": "",
        "Hover element": "",
        "id": 90
    },
    {
        "Page": "27",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "R stood for Romeo, H stood for Hotel",
        "Referenced": "NATO phonetic alphabet",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/NATO_phonetic_alphabet",
        "File": "",
        "Hover element": "",
        "id": 91
    },
    {
        "Page": "28",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Over the PA someone said, <i>Powerless, but not helpless</i>",
        "Referenced": "Alcoholics Anonymous",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 92
    },
    {
        "Page": "28",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "<i>How I love my babe-a-la, little baby girl</i>, I sang",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "A lullaby my mother sang to me as a child; I modified the lyrics.",
        "id": 93
    },
    {
        "Page": "28",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "She was everywhere, or starting to be everywhere",
        "Referenced": "Guillaume Apollinaire",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\u201cI am everywhere or rather I start to be everywhere / It is I who am starting this thing of the centuries to come\u201d",
        "id": 94
    },
    {
        "Page": "29",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Into a window, we used to put a decal of a hawk on the glass",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "My father installed one of these decals after birds repeatedly died flying into his living room window in California.",
        "id": 95
    },
    {
        "Page": "29",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "An album of photographs of his little boy",
        "Referenced": "Fullmetal Alchemist: Brotherhood",
        "Author": "",
        "Year": "2009",
        "Link": "",
        "File": "fma.png",
        "Hover element": "Fullmetal Alchemist: Brotherhood, season 1, episode 36 (\"Family Portrait\").",
        "id": 96
    },
    {
        "Page": "29",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Fugitive</i>, a scholar might say, regarding knowledge",
        "Referenced": "The Undercommons: Fugitive Planning & Black Study",
        "Author": "Fred Moten & Stefano Harney",
        "Year": "2013",
        "Link": "https://www.akpress.org/the-undercommons.html",
        "File": "",
        "Hover element": "",
        "id": 97
    },
    {
        "Page": "29",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "At the edge of one town a boy pressed one end of his flute",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "A performance by John Lincoln-Vogel in the Gila National Forest, high desert, with a small group of artists, c. 2014.",
        "id": 98
    },
    {
        "Page": "30",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "\u2014<i>I know she could kill me, and she chooses not to,</i> said daughter",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "My mother said this to me about our family dog, a German shepherd named Mishka.",
        "id": 99
    },
    {
        "Page": "30",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Ripe bananas just sat there like they weren\u2019t even scarce",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "A modified version of my mother's first impression of life outside the USSR, after first fleeing from Riga to Milan.",
        "id": 100
    },
    {
        "Page": "30",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "<i>Never show an idiot a half-finished job</i>, went the saying",
        "Referenced": "Russian idiom",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\u0414\u0443\u0440\u0430\u043a\u0443 \u043f\u043e\u043b\u0440\u0430\u0431\u043e\u0442\u044b \u043d\u0435 \u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u044e\u0442. (\"duraku pol rabotye ne pokazivaut\")",
        "id": 101
    },
    {
        "Page": "30",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Our eyes were staring, our mouths were open, our wings were spread",
        "Referenced": "On the Concept of History & Angelus Novus",
        "Author": "Walter Benjamin & Paul Klee",
        "Year": "1942",
        "Link": "https://www.sfu.ca/~andrewf/CONCEPT2.html",
        "File": "angelus-novus.jpg",
        "Hover element": "\"A Klee painting named \u2018Angelus Novus\u2019 shows an angel looking as though he is about to move away from something he is fixedly contemplating. His eyes are staring, his mouth is open, his wings are spread. This is how one pictures the angel of history. His face is turned toward the past. Where we perceive a chain of events, he sees one single catastrophe which keeps piling wreckage and hurls it in front of his feet. The angel would like to stay, awaken the dead, and make whole what has been smashed. But a storm is blowing in from Paradise; it has got caught in his wings with such a violence that the angel can no longer close them. The storm irresistibly propels him into the future to which his back is turned, while the pile of debris before him grows skyward. This storm is what we call progress.\"",
        "id": 102
    },
    {
        "Page": "30",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "When you touched something, it touched you back, I read that once",
        "Referenced": "Nausea",
        "Author": "Jean-Paul Sartre",
        "Year": "1938",
        "Link": "",
        "File": "",
        "Hover element": "\u201cObjects should not touch because they are not alive. You use them, put them back in place, you live among them: they are useful, nothing more. But they touch me, it is unbearable. I am afraid of being in contact with them as though they were living beasts.\u201d",
        "id": 103
    },
    {
        "Page": "30",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "They made a sound like grains of rice falling on a cymbal",
        "Referenced": "Ricefall",
        "Author": "Michael Pisaro",
        "Year": "",
        "Link": "https://www.youtube.com/watch?v=FXR4zm_C-ZA",
        "File": "",
        "Hover element": "",
        "id": 104
    },
    {
        "Page": "31",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Engage in commerce with the outside world",
        "Referenced": "Controversies in the Determination of Death: A White Paper by the President's Council on Bioethics",
        "Author": "",
        "Year": "2008",
        "Link": "https://www.thenewatlantis.com/wp-content/uploads/legacy-pdfs/20091130_determination_of_death.pdf",
        "File": "",
        "Hover element": "\"All organisms have a needy mode of being. Unlike inanimate objects, which continue to exist through inertia and without effort, every organism persists only thanks to its own exertions. To preserve themselves, organisms must\u2014and can and do\u2014engage in commerce with the surrounding world. Their constant need for oxygenated air and nutrients is matched by their ability to satisfy that need, by engaging in certain activities, reaching out into the surrounding environment to secure the required sustenance. This is the definitive work of the organism as an organism. It is what an organism \u201cdoes\u201d and what distinguishes every organism from non-living things.\"",
        "id": 105
    },
    {
        "Page": "31",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "The purpose of the rain was to be small and wet",
        "Referenced": "\"Natsukusa\"",
        "Author": "Annelyse Gelman",
        "Year": "2023",
        "Link": "",
        "File": "",
        "Hover element": "Song written at the Fondation Jan Michalski, inspired by Hiromi Ito's <i>Wild Grass on the Riverbank</i>.",
        "id": 106
    },
    {
        "Page": "32",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "One had a whole shelf of <i>To the Lighthouse</i>",
        "Referenced": "To the Lighthouse",
        "Author": "Virginia Woolf",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 107
    },
    {
        "Page": "32",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "<i>Eyeless and terrible</i>, said the book, and the book was right",
        "Referenced": "To the Lighthouse",
        "Author": "Virginia Woolf",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\"In spring the garden urns, casually filled with wind-blown plants, were gay as ever. Violets came and daffodils. But the stillness and the brightness of the day were as strange as the chaos and tumult of night, with the trees standing there, and the flowers standing there, looking before them, looking up, yet beholding nothing, eyeless, and thus terrible.\" (110)",
        "id": 108
    },
    {
        "Page": "32",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Pain was the shadow of a bird on the shadow of a branch",
        "Referenced": "\"Dreams\"",
        "Author": "Richard von Sturmer",
        "Year": "1993",
        "Link": "https://www.nzepc.auckland.ac.nz/features/taonga/sturmer.asp",
        "File": "",
        "Hover element": "\"The shadow of a cat sits on the shadow of a fence\"",
        "id": 109
    },
    {
        "Page": "32",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "An unprovoked act of senseless brutality was hardly mentioned",
        "Referenced": "Children of Men",
        "Author": "Alfonso Cuar\u00f3n",
        "Year": "2006",
        "Link": "https://www.bbc.com/news/uk-england-essex-34474620",
        "File": "",
        "Hover element": "",
        "id": 110
    },
    {
        "Page": "32",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "<i>The medium is the message</i>, went the saying",
        "Referenced": "Understanding Media: The Extensions of Man",
        "Author": "Marshall McLuhan",
        "Year": "1964",
        "Link": "https://en.wikipedia.org/wiki/The_medium_is_the_message",
        "File": "",
        "Hover element": "",
        "id": 111
    },
    {
        "Page": "32",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy with tenderness</i>, someone wrote, regarding a child\u2019s affections",
        "Referenced": "The Childhood of a Leader",
        "Author": "Jean-Paul Sartre",
        "Year": "1939",
        "Link": "",
        "File": "",
        "Hover element": "\"You said very quickly, \"Oh how I love my mamma,\" pronouncing it carefully and you saw mamma's face and felt all tender, you thought vaguely, vaguely, that God was watching you and afterwards you didn't think about it any more, you were all creamy with tenderness and then there were words dancing in your ears: mamma, MAMMA, MAMMA. That only lasted an instant, of course; it was like Lucien trying to balance a chair on his feet. But if, just at that moment, you said, \"Pacota,\" God had lost: He had only seen Good and what He saw engraved itself in His memory forever. But Lucien tired of this game because he had to make too much effort and besides you never knew whether God had won or lost.\"",
        "id": 112
    },
    {
        "Page": "32",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy pulp</i>, someone wrote, regarding a brain cut by a scalpel",
        "Referenced": "Methods of preparing, demonstrating, and examining cerebral structure in health and disease",
        "Author": "Bevan Lewis",
        "Year": "1881",
        "Link": "https://www.ncbi.nlm.nih.gov/books/NBK481829/",
        "File": "",
        "Hover element": "",
        "id": 113
    },
    {
        "Page": "32",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding a sumptuous evening",
        "Referenced": "Diary of Ana\u00efs Nin, Vol. 3",
        "Author": "Ana\u00efs Nin",
        "Year": "1939-1944",
        "Link": "",
        "File": "anais-nin-diary.png",
        "Hover element": "\"Canada was a generous, warmhearted host. He seemed to be whipping up excitement and expansiveness, creating a sumptuous creamy evening. His warm voice immersed you, his warm hand led you here and there, linking people, fusing them.\"",
        "id": 114
    },
    {
        "Page": "32",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "<i>Creamy</i>, someone wrote, regarding a flower\u2019s waxen flesh",
        "Referenced": "On Being Ill",
        "Author": "Virginia Woolf",
        "Year": "1930",
        "Link": "",
        "File": "",
        "Hover element": "\u201cNow perhaps one deliberately falls; now all the flowers, the voluptuous purple, the creamy, in whose waxen flesh the spoon had left a swirl of cherry juice; gladioli; dahlias; lilies, sacerdotal, ecclesiastical; flowers with prim cardboard collars tinged apricot and amber, all gently incline their heads to the breeze-all, with the exception of the heavy sunflower, who proudly acknowledges the sun at midday and perhaps at midnight rebuffs the moon.\u201d",
        "id": 115
    },
    {
        "Page": "32",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "Creamy, someone wrote, regarding a brook full of garbage",
        "Referenced": "Garbage",
        "Author": "A. R. Ammons",
        "Year": "1993",
        "Link": "",
        "File": "",
        "Hover element": "garbage has to be the poem of our time because<br>\ngarbage is spiritual, believable enough <br>\n <br><br>\nto get our attention, getting in the way, piling<br>\nup, stinking, turning brooks brownish and <br>\ncreamy white:  what else deflects us from the<br>\nerrors of our illusionary ways, not a temptation<br>\n <br><br>\nto trashlessness, that is too far off, and,<br>\nanyway, unimaginable, unrealistic<br>",
        "id": 116
    },
    {
        "Page": "32",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Flowers grew and bloomed and died and that was time passing",
        "Referenced": "Adaptation",
        "Author": "Charlie Kaufman",
        "Year": "2002",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 117
    },
    {
        "Page": "32",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Pain was the shadow of a bird on the shadow of a branch",
        "Referenced": "\"Dreams\"",
        "Author": "Richard von Sturmer",
        "Year": "1993",
        "Link": "https://www.nzepc.auckland.ac.nz/features/taonga/sturmer.asp",
        "File": "",
        "Hover element": "\"A pile of cigarette butts lies at the end of a long pier <br>\nIn a house by the sea, a man in his night-shirt is changing a light-bulb <br>\nIn the hair salon, a small girl places two red plastic straws in her hair <br>\nAn empty cassette box shines like a pool of water on a dark bedspread <br>\nThe shadow of a cat sits on the shadow of a fence\"<br>",
        "id": 118
    },
    {
        "Page": "33",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "People buying eggs got shot at the grocery store",
        "Referenced": "Mass shootings in the United States",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/List_of_mass_shootings_in_the_United_States",
        "File": "",
        "Hover element": "The shootings in <i>Vexations</i> are a combination of fiction and non-fiction. Many of these events, both \"invented\" and researched, have occurred repeatedly in real life as well as in media depictions, and are therefore impossible to trace to a single point of reference.",
        "id": 119
    },
    {
        "Page": "33",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "I thought it was firecrackers, said the DJ",
        "Referenced": "Pulse nightclub shooting",
        "Author": "",
        "Year": "2016",
        "Link": "https://www.nytimes.com/2016/06/13/us/last-call-at-orlando-club-and-then-the-shots-rang-out.html",
        "File": "",
        "Hover element": "",
        "id": 120
    },
    {
        "Page": "34",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "On his face there were black flies\u2014hundreds",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "2019",
        "Link": "",
        "File": "horse-flies-2.png",
        "Hover element": "Horse seen at the local stable in Montricher, Switzerland, while writing Vexations.",
        "id": 121
    },
    {
        "Page": "36",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Fireflies were beating against the walls, tap tap tap tap",
        "Referenced": "Wild Grass on the Riverbank",
        "Author": "Hiromi It\u014d",
        "Year": "2014",
        "Link": "https://actionbooks.org/hiromi-ito-wild-grass/",
        "File": "",
        "Hover element": "This cadence (and the ecological philosophy of Vexations) was inspired by Hiromi It\u014d's book-length poem 'The Wild Grass on the Riverbank'.",
        "id": 122
    },
    {
        "Page": "37",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "The community was a type of assistive technology, like a spiderweb",
        "Referenced": "Extended spider cognition",
        "Author": "Hilton F. Japyass\u00fa and Kevin N. Laland",
        "Year": "2017",
        "Link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5394149/",
        "File": "",
        "Hover element": "",
        "id": 123
    },
    {
        "Page": "38",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "I don\u2019t wanna have to kill myself",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "2018",
        "Link": "",
        "File": "",
        "Hover element": "Graffiti seen in Hyde Park, Austin, TX, 2018.",
        "id": 124
    },
    {
        "Page": "38",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Little blue buildings in a big green valley",
        "Referenced": "Little Boxes",
        "Author": "Malvina Reynolds",
        "Year": "",
        "Link": "https://www.youtube.com/watch?v=r5IKpHTEuY0",
        "File": "",
        "Hover element": "",
        "id": 125
    },
    {
        "Page": "38",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "There was no phonological loop, no visuospatial sketch pad",
        "Referenced": "Baddeley's model of working memory",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Baddeley%27s_model_of_working_memory",
        "File": "",
        "Hover element": "",
        "id": 126
    },
    {
        "Page": "38",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Onto the dusk-charged air we welded a new preposition",
        "Referenced": "Into the Dusk-Charged Air",
        "Author": "John Ashbery",
        "Year": "1997",
        "Link": "https://poets.org/poem/dusk-charged-air",
        "File": "",
        "Hover element": "",
        "id": 127
    },
    {
        "Page": "38",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "The acquisition window slid shut and I was feral forever",
        "Referenced": "Critical period hypothesis",
        "Author": "",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Critical_period_hypothesis",
        "File": "",
        "Hover element": "",
        "id": 128
    },
    {
        "Page": "39",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "A pigeon participated in a token economy",
        "Referenced": "Substitution effects in a generalized token economy with pigeons",
        "Author": "Leonardo F Andrade, Timothy D Hackenberg",
        "Year": "2017",
        "Link": "https://pubmed.ncbi.nlm.nih.gov/28000221/",
        "File": "",
        "Hover element": "",
        "id": 129
    },
    {
        "Page": "39",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Over the PA someone said, You don\u2019t really care for music, do ya?",
        "Referenced": "Hallelujah",
        "Author": "Leonard Cohen",
        "Year": "1984",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 130
    },
    {
        "Page": "40",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "\u2014It\u2019s a drawing of a HORSE in a cage",
        "Referenced": "The Little Prince (Le Petit Prince)",
        "Author": "Antoine de Saint-Exup\u00e9ry",
        "Year": "1943",
        "Link": "https://en.wikipedia.org/wiki/The_Little_Prince",
        "File": "hat-elephant.jpg",
        "Hover element": "",
        "id": 131
    },
    {
        "Page": "40",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Creamy, someone wrote, regarding a woman in a dress",
        "Referenced": "Suicide Club",
        "Author": "Rachel Heng",
        "Year": "2018",
        "Link": "https://www.rachelhengqp.com/suicide-club",
        "File": "",
        "Hover element": "\"It looked as if Natalie had been poured, a creamy, fragrant liquid, into the sleek dark length of it.\" (6)",
        "id": 132
    },
    {
        "Page": "40",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Creamy, the sharpened edge of a ceramic knife",
        "Referenced": "Suicide Club",
        "Author": "Rachel Heng",
        "Year": "2018",
        "Link": "https://www.rachelhengqp.com/suicide-club",
        "File": "",
        "Hover element": "\"Lea became aware of the weight of the knife in her other hand. It was a ceramic blade, newly sharpened to a fine creamy edge. There was a logic to it, bringing those two surfaces together, the tender shoot of her ring finger and that clean, objective line of the blade.\" (98)",
        "id": 133
    },
    {
        "Page": "40",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Creamy, a stone, limestone",
        "Referenced": "Loba",
        "Author": "Diane di Prima",
        "Year": "1973",
        "Link": "https://digitalcollections.poetshouse.org/digital-collection/chapbook-collection/Loba%2C-Part-1",
        "File": "",
        "Hover element": "\u201climestone is smooth / creamy / sparks blaze / like red & / fallen stars\u201d",
        "id": 134
    },
    {
        "Page": "40",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Over the PA someone said, You know your mother doesn\u2019t like to be disturbed when she\u2019s watching the war",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "2022",
        "Link": "",
        "File": "",
        "Hover element": "A comment my stepfather made, regarding Russia's war against Ukraine.",
        "id": 135
    },
    {
        "Page": "40",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Over the PA someone said, And the wisdom to know the difference",
        "Referenced": "Serenity prayer",
        "Author": "Alcoholics Anonymous",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\"Grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.\"",
        "id": 136
    },
    {
        "Page": "42",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "A plastic bag blew around in the visible spectrum",
        "Referenced": "American Beauty",
        "Author": "Sam Mendes",
        "Year": "1999",
        "Link": "https://www.youtube.com/watch?v=Qssvnjj5Moo",
        "File": "",
        "Hover element": "",
        "id": 137
    },
    {
        "Page": "42",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Rain is only rain in midair, went the saying",
        "Referenced": "\"How to Pray\"",
        "Author": "Annelyse Gelman",
        "Year": "2013",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 138
    },
    {
        "Page": "42",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "\u2014What\u2019s an ontological sickness? said daughter",
        "Referenced": "Personal experience of the author",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "Description of my manuscript Strawberry from a visiting poet at the Michener Center for Writers, 2018. Apparently a reference to Ren\u00e9 Girard.",
        "id": 139
    },
    {
        "Page": "42",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Indefinite postponement, said Hank",
        "Referenced": "Criminal Law: Indefinite Postponement of Sentence",
        "Author": "",
        "Year": "1958",
        "Link": "https://scholarship.law.ufl.edu/cgi/viewcontent.cgi?article=3237&context=flr",
        "File": "",
        "Hover element": "",
        "id": 140
    },
    {
        "Page": "42",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "\u2014I don\u2019t have access; I am access, said daughter",
        "Referenced": "Personal experience of the author",
        "Author": "Jason Grier",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "2016, Berlin, Germany.",
        "id": 141
    },
    {
        "Page": "43",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "Her back arched like a person that had just begun to be hit by a car",
        "Referenced": "Pies z g\u0142ow\u0105 (\u201cDog with a head\u201d)",
        "Author": "Auden Lincoln-Vogel",
        "Year": "2021",
        "Link": "https://audenlincolnvogel.com/pieszglowa",
        "File": "dog-with-head.jpg",
        "Hover element": "",
        "id": 142
    },
    {
        "Page": "43",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "A maid stood next to a window pouring milk",
        "Referenced": "The Milkmaid",
        "Author": "Johannes Vermeer",
        "Year": "1660",
        "Link": "https://en.wikipedia.org/wiki/The_Milkmaid_%28Vermeer%29",
        "File": "vermeer-milkmaid.jpg",
        "Hover element": "",
        "id": 143
    },
    {
        "Page": "43",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Over the PA someone said, Nor again is there anyone who loves or pursues or desires / To obtain pain of itself, because it is pain",
        "Referenced": "De finibus bonorum et malorum",
        "Author": "Cicero",
        "Year": "100 B.C.",
        "Link": "https://en.wikipedia.org/wiki/Lorem_ipsum",
        "File": "",
        "Hover element": "",
        "id": 144
    },
    {
        "Page": "44",
        "Stanza": "2",
        "Line from <i>Vexations</i>": "A spoken word is not a sparrow, went the saying",
        "Referenced": "Russian idiom",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 145
    },
    {
        "Page": "44",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "You could refuse all ideology, which was an ideology",
        "Referenced": "What is Art? Conversation with Joseph Beuys",
        "Author": "Joseph Beuys",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 146
    },
    {
        "Page": "44",
        "Stanza": "4",
        "Line from <i>Vexations</i>": "E.g., a boy pretending to catch and then eat a salmon",
        "Referenced": "Primitive Technology",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "",
        "id": 147
    },
    {
        "Page": "44",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "To reveal the wires, they opened daughter\u2019s wrists",
        "Referenced": "Metropolis",
        "Author": "Rintaro",
        "Year": "2001",
        "Link": "https://www.youtube.com/watch?v=85bL2uRdJ34",
        "File": "",
        "Hover element": "",
        "id": 148
    },
    {
        "Page": "45",
        "Stanza": "1",
        "Line from <i>Vexations</i>": "Under the asphalt, the treacherous goo",
        "Referenced": "La Brea tar pits",
        "Author": "",
        "Year": "",
        "Link": "",
        "File": "",
        "Hover element": "\"Treacherous Goo\" is written on informational signage at the La Brea Tar Pits in Los Angeles.",
        "id": 149
    },
    {
        "Page": "45",
        "Stanza": "3",
        "Line from <i>Vexations</i>": "Petals licked at her like flames exchanging softnesses",
        "Referenced": "\"A Boy and a Girl\" (Los Novios)",
        "Author": "Octavio Paz",
        "Year": "2008",
        "Link": "https://www.youtube.com/watch?v=GLoncQ9Euik",
        "File": "",
        "Hover element": "\"A Boy and a Girl\" was written by Octavio Paz and set for choir by Eric Whitacre:  \n\nStretched out on the grass,\na boy and a girl.\nSavoring their oranges,\ngiving their kisses \nlike waves exchanging foam.\n\nStretched out on the beach,\na boy and a girl.\nSavoring their limes,\ngiving their kisses \nlike clouds exchanging foam.\n\nStretched out underground,\na boy and a girl.\nSaying nothing, \nnever kissing,\ngiving silence \nfor silence.",
        "id": 150
    },
    {
        "Page": "45",
        "Stanza": "5",
        "Line from <i>Vexations</i>": "Lorem ipsum dolor in the shade",
        "Referenced": "Lorem ipsum",
        "Author": "Cicero",
        "Year": "",
        "Link": "https://en.wikipedia.org/wiki/Lorem_ipsum",
        "File": "",
        "Hover element": "\"Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally circumstances occur in which toil and pain can procure him some great pleasure.\"",
        "id": 151
    }
]

export default citations;